//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOHShaderModdingSupportLauncherWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class i18n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal i18n() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GOHShaderModdingSupportLauncherWPF.Properties.i18n", typeof(i18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Find a bug or get some interesting ideas? Tell our team about them on Github or Steam Workshop! 的本地化字符串。
        /// </summary>
        public static string A_BugReport {
            get {
                return ResourceManager.GetString("A_BugReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Github 的本地化字符串。
        /// </summary>
        public static string A_LinkGithub {
            get {
                return ResourceManager.GetString("A_LinkGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steam Workshop 的本地化字符串。
        /// </summary>
        public static string A_LinkWorkshop {
            get {
                return ResourceManager.GetString("A_LinkWorkshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 v1.9    by Federation Studio 2025 的本地化字符串。
        /// </summary>
        public static string A_Version {
            get {
                return ResourceManager.GetString("A_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Console 的本地化字符串。
        /// </summary>
        public static string C_Console {
            get {
                return ResourceManager.GetString("C_Console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable environment map support for all non-PBR materials (Experimental) 的本地化字符串。
        /// </summary>
        public static string C_EnableEnvMaps {
            get {
                return ResourceManager.GetString("C_EnableEnvMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target Path: 的本地化字符串。
        /// </summary>
        public static string C_Path {
            get {
                return ResourceManager.GetString("C_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Batch Convert Materials (mtl) 的本地化字符串。
        /// </summary>
        public static string C_Tab_MtlConvert {
            get {
                return ResourceManager.GetString("C_Tab_MtlConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Texture Channel Extraction/Injection 的本地化字符串。
        /// </summary>
        public static string C_Tab_TextureExtInj {
            get {
                return ResourceManager.GetString("C_Tab_TextureExtInj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Batch Remapping Texture Channels 的本地化字符串。
        /// </summary>
        public static string C_Tab_TextureRemap {
            get {
                return ResourceManager.GetString("C_Tab_TextureRemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View... 的本地化字符串。
        /// </summary>
        public static string C_ViewPath {
            get {
                return ResourceManager.GetString("C_ViewPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Fix (File Only) 的本地化字符串。
        /// </summary>
        public static string L_AutoFix {
            get {
                return ResourceManager.GetString("L_AutoFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DX 10.1 的本地化字符串。
        /// </summary>
        public static string L_DX101 {
            get {
                return ResourceManager.GetString("L_DX101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Editor 的本地化字符串。
        /// </summary>
        public static string L_Editor {
            get {
                return ResourceManager.GetString("L_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Replace (DX 11) 的本地化字符串。
        /// </summary>
        public static string L_FileReplace {
            get {
                return ResourceManager.GetString("L_FileReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main Game 的本地化字符串。
        /// </summary>
        public static string L_Main {
            get {
                return ResourceManager.GetString("L_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launch Mode 的本地化字符串。
        /// </summary>
        public static string L_Method {
            get {
                return ResourceManager.GetString("L_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show additional mod infomation 的本地化字符串。
        /// </summary>
        public static string L_ModInfo {
            get {
                return ResourceManager.GetString("L_ModInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Fix (Safe Mode) 的本地化字符串。
        /// </summary>
        public static string L_Safe {
            get {
                return ResourceManager.GetString("L_Safe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collect Shader Cache to Mod 的本地化字符串。
        /// </summary>
        public static string M_CollectCache {
            get {
                return ResourceManager.GetString("M_CollectCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string M_GridName {
            get {
                return ResourceManager.GetString("M_GridName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shader Included 的本地化字符串。
        /// </summary>
        public static string M_GridShader {
            get {
                return ResourceManager.GetString("M_GridShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        public static string M_GridType {
            get {
                return ResourceManager.GetString("M_GridType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load 的本地化字符串。
        /// </summary>
        public static string M_Load {
            get {
                return ResourceManager.GetString("M_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load Shader Cache 的本地化字符串。
        /// </summary>
        public static string M_LoadCache {
            get {
                return ResourceManager.GetString("M_LoadCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Mod Folder 的本地化字符串。
        /// </summary>
        public static string M_OpenFolder {
            get {
                return ResourceManager.GetString("M_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string M_Refresh {
            get {
                return ResourceManager.GetString("M_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Perform operations on selected mod: 的本地化字符串。
        /// </summary>
        public static string M_SelectedMod {
            get {
                return ResourceManager.GetString("M_SelectedMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unload 的本地化字符串。
        /// </summary>
        public static string M_Unload {
            get {
                return ResourceManager.GetString("M_Unload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 After Game Exits 的本地化字符串。
        /// </summary>
        public static string S_AfterGame {
            get {
                return ResourceManager.GetString("S_AfterGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically load shader cache (experimental) 的本地化字符串。
        /// </summary>
        public static string S_AutoLoadCache {
            get {
                return ResourceManager.GetString("S_AutoLoadCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Before Game Launches 的本地化字符串。
        /// </summary>
        public static string S_BeforeLaunch {
            get {
                return ResourceManager.GetString("S_BeforeLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Shader Cache 的本地化字符串。
        /// </summary>
        public static string S_Clear {
            get {
                return ResourceManager.GetString("S_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prompt shader compilation errors in game log 的本地化字符串。
        /// </summary>
        public static string S_CompileWarning {
            get {
                return ResourceManager.GetString("S_CompileWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game Configuration File Path:  的本地化字符串。
        /// </summary>
        public static string S_GameConfigPath {
            get {
                return ResourceManager.GetString("S_GameConfigPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to retrieve (common format: C:\Users\YOUR  USERNAME\Documents\my games\gates of hell), please enter manually. 的本地化字符串。
        /// </summary>
        public static string S_GameConfigPathTemplate {
            get {
                return ResourceManager.GetString("S_GameConfigPathTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redisplay launcher 的本地化字符串。
        /// </summary>
        public static string S_GameExit {
            get {
                return ResourceManager.GetString("S_GameExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game Path:  的本地化字符串。
        /// </summary>
        public static string S_GamePath {
            get {
                return ResourceManager.GetString("S_GamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to retrieve, please enter manually 的本地化字符串。
        /// </summary>
        public static string S_GamePathTemplate {
            get {
                return ResourceManager.GetString("S_GamePathTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        public static string S_General {
            get {
                return ResourceManager.GetString("S_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always ask if the game path is correct 的本地化字符串。
        /// </summary>
        public static string S_PathConfirm {
            get {
                return ResourceManager.GetString("S_PathConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh shader cache when shader files in loaded mods are modified 的本地化字符串。
        /// </summary>
        public static string S_RefreshCache {
            get {
                return ResourceManager.GetString("S_RefreshCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore vanilla Shader File 的本地化字符串。
        /// </summary>
        public static string S_Restore {
            get {
                return ResourceManager.GetString("S_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GOH SMS Launcher 的本地化字符串。
        /// </summary>
        public static string StatusBar_Title {
            get {
                return ResourceManager.GetString("StatusBar_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string Tab_About {
            get {
                return ResourceManager.GetString("Tab_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Texture and Material Converter 的本地化字符串。
        /// </summary>
        public static string Tab_Converter {
            get {
                return ResourceManager.GetString("Tab_Converter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launcher 的本地化字符串。
        /// </summary>
        public static string Tab_Launcher {
            get {
                return ResourceManager.GetString("Tab_Launcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mod Manager 的本地化字符串。
        /// </summary>
        public static string Tab_ModManager {
            get {
                return ResourceManager.GetString("Tab_ModManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Tab_Settings {
            get {
                return ResourceManager.GetString("Tab_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Utilities 的本地化字符串。
        /// </summary>
        public static string Tab_Tools {
            get {
                return ResourceManager.GetString("Tab_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gate of Hell Shader Modding Support Launcher 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear All Shader Cache and Records 的本地化字符串。
        /// </summary>
        public static string U_ClearAllCache {
            get {
                return ResourceManager.GetString("U_ClearAllCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Shader Cache Folder 的本地化字符串。
        /// </summary>
        public static string U_OpenCacheFolder {
            get {
                return ResourceManager.GetString("U_OpenCacheFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Configuration File of Launcher 的本地化字符串。
        /// </summary>
        public static string U_OpenLauncherConfig {
            get {
                return ResourceManager.GetString("U_OpenLauncherConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Precompile All Shader to Cache (DX 11 Only) 的本地化字符串。
        /// </summary>
        public static string U_Precompile {
            get {
                return ResourceManager.GetString("U_Precompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore Default Shader File (For File Replace Mode Only) 的本地化字符串。
        /// </summary>
        public static string U_Restore {
            get {
                return ResourceManager.GetString("U_Restore", resourceCulture);
            }
        }
    }
}
