//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOHShaderModdingSupportLauncherWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class i18n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal i18n() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GOHShaderModdingSupportLauncherWPF.Properties.i18n", typeof(i18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Default Game (DX 10.1) 的本地化字符串。
        /// </summary>
        public static string L_DGDX {
            get {
                return ResourceManager.GetString("L_DGDX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default Game (File Replace) 的本地化字符串。
        /// </summary>
        public static string L_DGFR {
            get {
                return ResourceManager.GetString("L_DGFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Editor (DX 10.1) 的本地化字符串。
        /// </summary>
        public static string L_EDX {
            get {
                return ResourceManager.GetString("L_EDX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Editor (File Replace) 的本地化字符串。
        /// </summary>
        public static string L_EFR {
            get {
                return ResourceManager.GetString("L_EFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Safe Mode (Auto Fix) 的本地化字符串。
        /// </summary>
        public static string L_Safe {
            get {
                return ResourceManager.GetString("L_Safe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Shader Cache after game exit 的本地化字符串。
        /// </summary>
        public static string S_Clear {
            get {
                return ResourceManager.GetString("S_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore vanilla Shader File after game exit 的本地化字符串。
        /// </summary>
        public static string S_Restore {
            get {
                return ResourceManager.GetString("S_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GOH SMS Launcher 的本地化字符串。
        /// </summary>
        public static string StatusBar_Title {
            get {
                return ResourceManager.GetString("StatusBar_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launcher 的本地化字符串。
        /// </summary>
        public static string Tab_Launcher {
            get {
                return ResourceManager.GetString("Tab_Launcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Tab_Settings {
            get {
                return ResourceManager.GetString("Tab_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tools 的本地化字符串。
        /// </summary>
        public static string Tab_Tools {
            get {
                return ResourceManager.GetString("Tab_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gate of Hell Shader Modding Support Launcher 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
