//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOHShaderModdingSupportLauncherWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class i18n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal i18n() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GOHShaderModdingSupportLauncherWPF.Properties.i18n", typeof(i18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Find a bug or get some interesting ideas? Tell our team about them on Github or Steam Workshop! 的本地化字符串。
        /// </summary>
        public static string A_BugReport {
            get {
                return ResourceManager.GetString("A_BugReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Github 的本地化字符串。
        /// </summary>
        public static string A_LinkGithub {
            get {
                return ResourceManager.GetString("A_LinkGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steam Workshop 的本地化字符串。
        /// </summary>
        public static string A_LinkWorkshop {
            get {
                return ResourceManager.GetString("A_LinkWorkshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 v1.92    by Federation Studio 2025 的本地化字符串。
        /// </summary>
        public static string A_Version {
            get {
                return ResourceManager.GetString("A_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Captured exception message:   的本地化字符串。
        /// </summary>
        public static string APP_ExceptionMessage {
            get {
                return ResourceManager.GetString("APP_ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Captured exception type:  的本地化字符串。
        /// </summary>
        public static string APP_ExceptionType {
            get {
                return ResourceManager.GetString("APP_ExceptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root exception message:  的本地化字符串。
        /// </summary>
        public static string APP_RootMessage {
            get {
                return ResourceManager.GetString("APP_RootMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root exception type:  的本地化字符串。
        /// </summary>
        public static string APP_RootType {
            get {
                return ResourceManager.GetString("APP_RootType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stack trace:  的本地化字符串。
        /// </summary>
        public static string APP_Stack {
            get {
                return ResourceManager.GetString("APP_Stack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time:  的本地化字符串。
        /// </summary>
        public static string APP_Time {
            get {
                return ResourceManager.GetString("APP_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Type:  的本地化字符串。
        /// </summary>
        public static string APP_Type {
            get {
                return ResourceManager.GetString("APP_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Console 的本地化字符串。
        /// </summary>
        public static string C_Console {
            get {
                return ResourceManager.GetString("C_Console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable environment map support for all non-PBR materials (Experimental) 的本地化字符串。
        /// </summary>
        public static string C_EnableEnvMaps {
            get {
                return ResourceManager.GetString("C_EnableEnvMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 mtl convert complete! 的本地化字符串。
        /// </summary>
        public static string C_MtlComplete {
            get {
                return ResourceManager.GetString("C_MtlComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 has been updated. 的本地化字符串。
        /// </summary>
        public static string C_MtlUpdated {
            get {
                return ResourceManager.GetString("C_MtlUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A .mtl file with path 的本地化字符串。
        /// </summary>
        public static string C_NormalMtl {
            get {
                return ResourceManager.GetString("C_NormalMtl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A .mtl file in 的本地化字符串。
        /// </summary>
        public static string C_PakMtl0 {
            get {
                return ResourceManager.GetString("C_PakMtl0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 with path 的本地化字符串。
        /// </summary>
        public static string C_PakMtl1 {
            get {
                return ResourceManager.GetString("C_PakMtl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target Path: 的本地化字符串。
        /// </summary>
        public static string C_Path {
            get {
                return ResourceManager.GetString("C_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path not found! 的本地化字符串。
        /// </summary>
        public static string C_PathNotFound {
            get {
                return ResourceManager.GetString("C_PathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Batch Convert Materials (mtl) 的本地化字符串。
        /// </summary>
        public static string C_Tab_MtlConvert {
            get {
                return ResourceManager.GetString("C_Tab_MtlConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Texture Channel Extraction/Injection 的本地化字符串。
        /// </summary>
        public static string C_Tab_TextureExtInj {
            get {
                return ResourceManager.GetString("C_Tab_TextureExtInj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Batch Remapping Texture Channels 的本地化字符串。
        /// </summary>
        public static string C_Tab_TextureRemap {
            get {
                return ResourceManager.GetString("C_Tab_TextureRemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View... 的本地化字符串。
        /// </summary>
        public static string C_ViewPath {
            get {
                return ResourceManager.GetString("C_ViewPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Fix (File Only) 的本地化字符串。
        /// </summary>
        public static string L_AutoFix {
            get {
                return ResourceManager.GetString("L_AutoFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DX 10.1 的本地化字符串。
        /// </summary>
        public static string L_DX101 {
            get {
                return ResourceManager.GetString("L_DX101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Editor 的本地化字符串。
        /// </summary>
        public static string L_Editor {
            get {
                return ResourceManager.GetString("L_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Replace (DX 11) 的本地化字符串。
        /// </summary>
        public static string L_FileReplace {
            get {
                return ResourceManager.GetString("L_FileReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main Game 的本地化字符串。
        /// </summary>
        public static string L_Main {
            get {
                return ResourceManager.GetString("L_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launch Mode 的本地化字符串。
        /// </summary>
        public static string L_Method {
            get {
                return ResourceManager.GetString("L_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show additional mod infomation 的本地化字符串。
        /// </summary>
        public static string L_ModInfo {
            get {
                return ResourceManager.GetString("L_ModInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Fix (Safe Mode) 的本地化字符串。
        /// </summary>
        public static string L_Safe {
            get {
                return ResourceManager.GetString("L_Safe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shader Cache from this mod has been loaded.
        ///If you are sure it is not please manually clear all cache from Utilities page. 的本地化字符串。
        /// </summary>
        public static string M_CacheHasBeenLoaded {
            get {
                return ResourceManager.GetString("M_CacheHasBeenLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collect Shader Cache to Mod 的本地化字符串。
        /// </summary>
        public static string M_CollectCache {
            get {
                return ResourceManager.GetString("M_CollectCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cache collecting complete! 的本地化字符串。
        /// </summary>
        public static string M_CollectCacheSuccessful {
            get {
                return ResourceManager.GetString("M_CollectCacheSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string M_GridName {
            get {
                return ResourceManager.GetString("M_GridName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shader Included 的本地化字符串。
        /// </summary>
        public static string M_GridShader {
            get {
                return ResourceManager.GetString("M_GridShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        public static string M_GridType {
            get {
                return ResourceManager.GetString("M_GridType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load 的本地化字符串。
        /// </summary>
        public static string M_Load {
            get {
                return ResourceManager.GetString("M_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load Shader Cache 的本地化字符串。
        /// </summary>
        public static string M_LoadCache {
            get {
                return ResourceManager.GetString("M_LoadCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successfully load all Shader Cache. 的本地化字符串。
        /// </summary>
        public static string M_LoadCacheSuccessful {
            get {
                return ResourceManager.GetString("M_LoadCacheSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No cache to collect. 的本地化字符串。
        /// </summary>
        public static string M_NoCacheToCollect {
            get {
                return ResourceManager.GetString("M_NoCacheToCollect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Shader Cache found in selected mod. 的本地化字符串。
        /// </summary>
        public static string M_NoCacheToLoad {
            get {
                return ResourceManager.GetString("M_NoCacheToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Mod Folder 的本地化字符串。
        /// </summary>
        public static string M_OpenFolder {
            get {
                return ResourceManager.GetString("M_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string M_Refresh {
            get {
                return ResourceManager.GetString("M_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Perform operations on selected mod: 的本地化字符串。
        /// </summary>
        public static string M_SelectedMod {
            get {
                return ResourceManager.GetString("M_SelectedMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collecting caches to Workshop mods is not allowed! 的本地化字符串。
        /// </summary>
        public static string M_TryCollectWorkshopMod {
            get {
                return ResourceManager.GetString("M_TryCollectWorkshopMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unload 的本地化字符串。
        /// </summary>
        public static string M_Unload {
            get {
                return ResourceManager.GetString("M_Unload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get error when reading launcher config file! Will delete invalid config file. 的本地化字符串。
        /// </summary>
        public static string Main_ErrorReadConfig {
            get {
                return ResourceManager.GetString("Main_ErrorReadConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get error when reading mod.info file! Error= 的本地化字符串。
        /// </summary>
        public static string Main_ErrorReadModInfo {
            get {
                return ResourceManager.GetString("Main_ErrorReadModInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A GOH game has been found in 的本地化字符串。
        /// </summary>
        public static string Main_FoundGame0 {
            get {
                return ResourceManager.GetString("Main_FoundGame0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If this is NOT the correct location. Please click NO and report detailed information to developers. 的本地化字符串。
        /// </summary>
        public static string Main_FoundGame1 {
            get {
                return ResourceManager.GetString("Main_FoundGame1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maunal Check 的本地化字符串。
        /// </summary>
        public static string Main_MaunalCheck {
            get {
                return ResourceManager.GetString("Main_MaunalCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Failed to Get Name] 的本地化字符串。
        /// </summary>
        public static string Main_ModErrorName {
            get {
                return ResourceManager.GetString("Main_ModErrorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local 的本地化字符串。
        /// </summary>
        public static string Main_ModLocal {
            get {
                return ResourceManager.GetString("Main_ModLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workshop 的本地化字符串。
        /// </summary>
        public static string Main_ModWorkshop {
            get {
                return ResourceManager.GetString("Main_ModWorkshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not find GOH game on your computer! 的本地化字符串。
        /// </summary>
        public static string Main_NoGame {
            get {
                return ResourceManager.GetString("Main_NoGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not find GOH user profile on your computer! 的本地化字符串。
        /// </summary>
        public static string Main_NoProfile {
            get {
                return ResourceManager.GetString("Main_NoProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not find steamapps folder on your computer! 的本地化字符串。
        /// </summary>
        public static string Main_NoSteam {
            get {
                return ResourceManager.GetString("Main_NoSteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please run GOH game at least once before using this program! 的本地化字符串。
        /// </summary>
        public static string Main_RunGameOnce {
            get {
                return ResourceManager.GetString("Main_RunGameOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get at least one shader compile error in last gaming! 
        ///Try contact creator(s) of your shader mod to slove this problem. 的本地化字符串。
        /// </summary>
        public static string Main_ShaderCompileErrorMessage0 {
            get {
                return ResourceManager.GetString("Main_ShaderCompileErrorMessage0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First error message founded: 的本地化字符串。
        /// </summary>
        public static string Main_ShaderCompileErrorMessage1 {
            get {
                return ResourceManager.GetString("Main_ShaderCompileErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shader Compile Error 的本地化字符串。
        /// </summary>
        public static string Main_ShaderCompileErrorTitle {
            get {
                return ResourceManager.GetString("Main_ShaderCompileErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 After Game Exits 的本地化字符串。
        /// </summary>
        public static string S_AfterGame {
            get {
                return ResourceManager.GetString("S_AfterGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically load shader cache (experimental) 的本地化字符串。
        /// </summary>
        public static string S_AutoLoadCache {
            get {
                return ResourceManager.GetString("S_AutoLoadCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Before Game Launches 的本地化字符串。
        /// </summary>
        public static string S_BeforeLaunch {
            get {
                return ResourceManager.GetString("S_BeforeLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Shader Cache 的本地化字符串。
        /// </summary>
        public static string S_Clear {
            get {
                return ResourceManager.GetString("S_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prompt shader compilation errors in game log 的本地化字符串。
        /// </summary>
        public static string S_CompileWarning {
            get {
                return ResourceManager.GetString("S_CompileWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game Configuration File Path:  的本地化字符串。
        /// </summary>
        public static string S_GameConfigPath {
            get {
                return ResourceManager.GetString("S_GameConfigPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to retrieve (common format: C:\Users\YOUR  USERNAME\Documents\my games\gates of hell), please enter manually. 的本地化字符串。
        /// </summary>
        public static string S_GameConfigPathTemplate {
            get {
                return ResourceManager.GetString("S_GameConfigPathTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redisplay launcher 的本地化字符串。
        /// </summary>
        public static string S_GameExit {
            get {
                return ResourceManager.GetString("S_GameExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game Path:  的本地化字符串。
        /// </summary>
        public static string S_GamePath {
            get {
                return ResourceManager.GetString("S_GamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to retrieve, please enter manually 的本地化字符串。
        /// </summary>
        public static string S_GamePathTemplate {
            get {
                return ResourceManager.GetString("S_GamePathTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        public static string S_General {
            get {
                return ResourceManager.GetString("S_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always ask if the game path is correct 的本地化字符串。
        /// </summary>
        public static string S_PathConfirm {
            get {
                return ResourceManager.GetString("S_PathConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh shader cache when shader files in loaded mods are modified 的本地化字符串。
        /// </summary>
        public static string S_RefreshCache {
            get {
                return ResourceManager.GetString("S_RefreshCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore vanilla Shader File 的本地化字符串。
        /// </summary>
        public static string S_Restore {
            get {
                return ResourceManager.GetString("S_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GOH SMS Launcher 的本地化字符串。
        /// </summary>
        public static string StatusBar_Title {
            get {
                return ResourceManager.GetString("StatusBar_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string Tab_About {
            get {
                return ResourceManager.GetString("Tab_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Texture and Material Converter 的本地化字符串。
        /// </summary>
        public static string Tab_Converter {
            get {
                return ResourceManager.GetString("Tab_Converter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launcher 的本地化字符串。
        /// </summary>
        public static string Tab_Launcher {
            get {
                return ResourceManager.GetString("Tab_Launcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mod Manager 的本地化字符串。
        /// </summary>
        public static string Tab_ModManager {
            get {
                return ResourceManager.GetString("Tab_ModManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Tab_Settings {
            get {
                return ResourceManager.GetString("Tab_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Utilities 的本地化字符串。
        /// </summary>
        public static string Tab_Tools {
            get {
                return ResourceManager.GetString("Tab_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gate of Hell Shader Modding Support Launcher 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear All Shader Cache and Records 的本地化字符串。
        /// </summary>
        public static string U_ClearAllCache {
            get {
                return ResourceManager.GetString("U_ClearAllCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shader cache cleanup complete! 的本地化字符串。
        /// </summary>
        public static string U_ClearAllCacheSuccessful {
            get {
                return ResourceManager.GetString("U_ClearAllCacheSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Shader Cache Folder 的本地化字符串。
        /// </summary>
        public static string U_OpenCacheFolder {
            get {
                return ResourceManager.GetString("U_OpenCacheFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Configuration File of Launcher 的本地化字符串。
        /// </summary>
        public static string U_OpenLauncherConfig {
            get {
                return ResourceManager.GetString("U_OpenLauncherConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Precompile All Shader to Cache (DX 11 Only) 的本地化字符串。
        /// </summary>
        public static string U_Precompile {
            get {
                return ResourceManager.GetString("U_Precompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore Default Shader File (For File Replace Mode Only) 的本地化字符串。
        /// </summary>
        public static string U_Restore {
            get {
                return ResourceManager.GetString("U_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore default shader file successful! 的本地化字符串。
        /// </summary>
        public static string U_RestoreSuccessful {
            get {
                return ResourceManager.GetString("U_RestoreSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ERROR 的本地化字符串。
        /// </summary>
        public static string Universal_Error {
            get {
                return ResourceManager.GetString("Universal_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notice 的本地化字符串。
        /// </summary>
        public static string Universal_Notice {
            get {
                return ResourceManager.GetString("Universal_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        public static string Universal_Warning {
            get {
                return ResourceManager.GetString("Universal_Warning", resourceCulture);
            }
        }
    }
}
